### ISSUE TITLE
unable to open Context menu in TV guide (tvheadend/Kodi 19/Shield)

### ISSUE THREAD

**Issue by CanberraPete** [xbmc/skin.confluence#103]
Hi.
After upgrading to Kodi 19 (Nvidia Shield) I am no longer able to open the context/submenu when in the TV guide (used to "long press" the select key and it would display a menu to show information - select recording etc.  I've configured KODI/PVR client to change channel on "short" pressing select).

I "think" it's trying to work as when I look at the log the following appears after a long press of the select key.

_**_2021-03-16 21:26:06.031 T:20346    INFO <general>: Loading skin file: DialogPVRGuideControls.xml, load type: KEEP_IN_MEMORY
2021-03-16 21:26:06.032 T:20346   ERROR <general>: Unable to load window XML: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/skin.confluence/720p/DialogPVRGuideControls.xml. Line 0
                                                   Failed to open file_**_
                                                   
I don't know enough about it to go find the xml file myself.
Thanks,
Pete.

**Comment by gade01** [comment]
@CanberraPete 
Thanks a lot for reporting this.

That's a new dialog for Kodi 19 that has not yet been added to Confluence.
I'll look at adding it soon :)

Cheers
Gade

**Comment by github-catch-22** [comment]
Hi
Like the skin. It's fast and works well on a low spec machine. I would love to help to get the PVR/Live TV menus in there. How can I help. I know very little about Kodi skinning internals but am willing to learn.

**Comment by gade01** [comment]
PR's are done:

https://github.com/xbmc/skin.confluence/pull/109
https://github.com/xbmc/skin.confluence/pull/110

**Comment by gade01** [comment]
PR's are merged. 

I'll PR an updated version to the Kodi repo soon.
