### ISSUE TITLE
[v4.6.9] Subtitle icon always showing on Leia 18.x, regardless of subtitles being active

### ISSUE THREAD

**Issue by Drag0nFly** [xbmc/skin.confluence#104]
_[ First of all, Confluence is by far my favorite skin on Kodi (still) – many thanks for maintaining it. It makes the whole cinematic experience so much cleaner and functional, IMO. ]_

However there is a change in behaviour from the Leia branch compared to prior Kodi versions for this skin which impacts the status line (activated by pressing "i")  – the icon for subtitle languange (e.g, "en" for English) is always present even if the subtitle has been switched off (with "t").

I've noticed this on several Leia installations; ranging from 18.3 to 18.7, running on Parabola Linux and also on Raspbian (Rpi4); the behaviour is the same. Also the same behaviour when compiling from source and reinstalling the Confluence add-on.

On prior versions of Kodi the icon for subtitle language was not present if a subtitle was currently not showing, which is what one would expect (it would re-appear if the subtitle was toggled back on, and "i", or the appropriate remote-control button mapping pressed.)

Hopefully this is a simple fix.

**Comment by gade01** [comment]
I submitted a PR with a fix.

**Comment by gade01** [comment]
PR's are merged.
