### ISSUE TITLE
[v4.6.9] 'Programs' menu item missing on Leia 18.x; cannot be toggled active in settings

### ISSUE THREAD

**Issue by Drag0nFly** [xbmc/skin.confluence#113]
The main menu item, 'Programs' is missing in recent Confluence versions on Leia. Previously this could be toggled via System->Appearance->Skin settings, but the Programs entry is altogether missing from the list (entries which can be toggled are 'Weather', 'Movies', TV Shows', 'Music', etc.

I frequently rely on using the Programs menu-item to quickly access program addons, which now take 4-5 more steps to find, selecting the add-on, and choosing 'Run'; which is as one might agree a lot more cumbersome.

**Comment by HitcherUK** [comment]
'Add-ons' will take you to Program Addons.

**Comment by Drag0nFly** [comment]
@HitcherUK – thought I already tried 'Add-Ons', my mistake.

Thank you! Closing.
