### ISSUE TITLE
DialogPlayerProcessInfo

### ISSUE THREAD

**Issue by kengithub9** [xbmc/skin.confluence#119]
Hi, is it possible to build Estuary's DialogPlayerProcessInfo into the Confluence skin in Kodi 19 now some things aren't quite right? 
In Kodi 18 everything is fine.

**Comment by gade01** [comment]
Hi @kengithub9 
Can you please explain in detail what isn't quite right?
For me they display the exact same info, but in different places.

CONFLUENCE
![screenshot00003](https://user-images.githubusercontent.com/4256581/115695631-42563300-a362-11eb-8cfa-58e98848f353.png)

ESTUARY
![screenshot00004](https://user-images.githubusercontent.com/4256581/115695534-2fdbf980-a362-11eb-8894-1e9f90905bfc.png)

**Comment by kengithub9** [comment]
I had downloaded a modified version with more info from CoreElec forum where some words have been dropped that are in the other skin. I have my version below, maybe you can check what's missing? 

[DialogPlayerProcessInfo (New).zip](https://github.com/xbmc/skin.confluence/files/6367557/DialogPlayerProcessInfo.New.zip)

**Comment by HitcherUK** [comment]
So you want us to add something to Confluence that is a mod of Estuary?

**Comment by kengithub9** [comment]
Nowadays that info is standard in the skin of Kodi 19,
but I don't understand the codes myself, so maybe you can add it in the skin.

**Comment by harryberlin** [comment]
you should tell exactly which info you miss. uploading zip files or say coreelec has this, is not helpful.

**Comment by kengithub9** [comment]
Info for display mode, pixel format and EOFT & Gamut. 
average bitrate for audio en video.

**Comment by HitcherUK** [comment]
> Nowadays that info is standard in the skin of Kodi 19,

But it's not in Estuary!

**Comment by kengithub9** [comment]
Here are screenshots of how I see it.
The red touched is what is not quite right. 
![confluence skin](https://user-images.githubusercontent.com/56362494/115994674-4ab7a380-a5d8-11eb-9b38-2b3d6bb391c3.jpg)
![Estuary skin](https://user-images.githubusercontent.com/56362494/115994678-4d19fd80-a5d8-11eb-89e4-b40d599ca2dc.jpg)

**Comment by kengithub9** [comment]
![skin](https://user-images.githubusercontent.com/56362494/115995110-3bd1f080-a5da-11eb-911e-ec57e803d6d2.jpeg)
It could be that way.

**Comment by HitcherUK** [comment]
I can't even find those labels in the wiki?

https://kodi.wiki/view/InfoLabels#Player_labels

**Comment by kengithub9** [comment]
That's strange, then people added it themselves.
Here the codes they used:
Window(10000).Property(amlogic.DisplayMode)
Window(10000).Property(amlogic.ColourDepth)
Window(10000).Property(amlogic.ColourSpace)
Window(10000).Property(amlogic.ColourRange)
Window(10000).Property(amlogic.EOTF)
Window(10000).Property(amlogic.Colourimetry)

**Comment by HitcherUK** [comment]
Those are window properties that have either been set by a script or are CoreElec specific.

**Comment by gade01** [comment]
All those properties are added by a custom script:
https://discourse.coreelec.org/t/amlogic-color-space-depth-information-addon/4675

If they exist somewhere, it's because someone has added the script and made custom skin xml files.

**Comment by kengithub9** [comment]
I get it, and I thought it wouldn't be standard in kodi, but it could also be that kodi19 has changed many things, causing many things to stop working.

**Comment by gade01** [comment]
Addons have to be ported to Python 3 to work in Kodi 19.

If the script, providing these info labels, doesn't work in Kodi 19, you should contact the developer.

**Comment by HitcherUK** [comment]
Closing this as we're definitely not going to add labels from a 3rd party script.
