### ISSUE TITLE
A couple of typos in the greek translation

### ISSUE THREAD

**Issue by pitsi** [xbmc/skin.confluence#122]
Please change `Εμφάνηση` (lines 257 and 261 in the greek strings.po) to `Εμφάνιση` (as seen in line 241 and a few more).
Above that, on line 269, `απτικοποίηση` should be `oπτικοποίηση`. Those 2 hurt my eyes :P 

Moreover, the same lines could be changed from
```
"Εμφάνηση φόντου βίντεο που \"Αναπαραγωγή σε εκτέλεση\""
"Εμφάνηση φόντου οπτικοποίησης που \"Αναπαραγωγή σε εκτέλεση\""
```
to
```
"Εμφάνιση φόντου βίντεο όταν γίνεται \"Αναπαραγωγή σε εκτέλεση\""
"Εμφάνιση φόντου οπτικοποίησης όταν γίνεται \"Αναπαραγωγή σε εκτέλεση\""
```
In rough translation, it means "when `playback` occurs", but it sounds better than the existing one. 

If there are any other strings that need to be translated, please tell me.

**Comment by gade01** [comment]
Hi @pitsi 

Thanks a lot for reporting this.
I have changed the lines blindly, as I have no idea what I'm doing :)

Please check if the changes are correct:
https://github.com/xbmc/skin.confluence/pull/123/files#diff-ee19bd6a9e58131cf0d03a835b3a606fde68658b48a9117282482286443ea8db

You are more than welcome to join Weblate to translate Kodi and all addons to Greek.
https://kodi.weblate.cloud/accounts/register/
If you do, please let me know your username and which language team you would like to have access to in this forum thread: 
https://forum.kodi.tv/showthread.php?tid=363132

**Comment by pitsi** [comment]
They seem fine, although there is some missmatch on the line numbers. What I reported above really is on the forementioned lines on this file. I guess that is not an issue.
https://github.com/xbmc/skin.confluence/blob/master/language/resource.language.el_gr/strings.po

On the other hand, I have no time for massive translations, sorry. If I decide to join weblate one day, I will let you know.

**Comment by gade01** [comment]
The mismatch is because you look at the master branch.

I have PR'd Matrix branch which is the active branch for Kodi 19.

I'll merge the PR. 

Thanks again for reporting the issues. 
And if you decide to join Weblate, just ping me 😉
