### ISSUE TITLE
No textures for Confluence with Nexus

### ISSUE THREAD

**Issue by howie-f** [xbmc/skin.confluence#149]
not sure if somebody is already aware of this. installing confluence under current master looks like this

![screenshot00000](https://user-images.githubusercontent.com/58829855/135842849-3c9c7793-8edb-4856-b4b8-4eab05aeeb29.png)
![screenshot00001](https://user-images.githubusercontent.com/58829855/135842872-b0bb6af9-07c6-44be-bc85-1338fc6cb22b.png)

all good when installing under Matrix

**Comment by gade01** [comment]
@howie-f I can confirm this.
It seems confluence is submitted to the Nexus repo. But the Textures.xbt file is only 9 byte.

**Comment by gade01** [comment]
Last PR's are by me, but only for Leia and Matrix repos.
@ronie Any idea what hapened?

**Comment by howie-f** [comment]
i was a bit surprised that confluence is available in the nexus repo. is that intended?

**Comment by gade01** [comment]
I don't think so.
No big changes are added between the two branches.
I submitted Confluence for Leia and Matrix, but not for Nexus.

**Comment by ronie** [comment]
matrix skins are indeed available to kodi matrix, which is intentional.
else there wouldn't be any skins (or any addons at all) available to kodi matrix,
since no skins (or other addons) have been submitted to the nexus repo yet.

the repo logic is defined by this file:
https://github.com/xbmc/repo-scripts/blob/97b2f3e83a6a09b58ff19d562c66e9d8a2a72f9d/targets.cfg#L88-L95
to matrix users, we serve all addons from the gotham to nexus branches, if the addons meets the defined `minversions`.

**Comment by ronie** [comment]
@gade01 i had a bit of time to look into it but i have no idea what caused the corrupt Textures.xbt.
if i compile the Textures file locally, using Texturepacker from master, it succeeds without any issues.

perhaps you can do another PR for Confluence?

**Comment by gade01** [comment]
@ronie I could.
The issue is that no one (afaik) ever submitted Confluence to Nexus repo.
That's what I didn't understand in the above posts.

Thanks a lot for looking into this.

**Comment by ronie** [comment]
> Confluence has no media files in the repo, only an already compressed Textures file.

damn, yeah, that must be it. obviously something i messed up after the last PR was merged into Matrix.
i'll merge the new PR right away and keep an eye on things, though i'm sure all should be ok now.

**Comment by gade01** [comment]
Thanks a lot :)

**Comment by gade01** [comment]
@howie-f The issue should be solved now?

**Comment by howie-f** [comment]
hi @gade01 and @ronie 
yup, looks pretty good now. like we‘re used to. thanks
