### ISSUE TITLE
CU LRC Lyrics list control 120 is not used anymore

### ISSUE THREAD

**Issue by arnesongit** [xbmc/skin.confluence#173]
The script-cu-lrclyrics-main.xml file still contains the list control 120 which is not used anymore in the CU LRC Lyrics adddon since version 6.30,  see here: https://forum.kodi.tv/showthread.php?tid=147340&pid=3094059#pid3094059

Please remove this or make it unvisible with 
`<visible>false</visible>`

The list control 120 is drawn over the 110 lyrics list, see here: https://forum.kodi.tv/showthread.php?tid=147340&pid=3093922#pid3093922

**Comment by gade01** [comment]
@arnesongit Thanks for creating this issue and bringing it to our attention.

I'll look at this when I have some time. Should be an easy fix ;)
