### ISSUE TITLE
[feature request] support native 4k

### ISSUE THREAD

**Issue by J4gQBqqR** [xbmc/skin.confluence#174]
Hi, thanks for making this awesome skin.
As 4K becomes mainstream, would you consider making the skin native in 4K? 

I know it goes way beyond updating wallpaper and probably requires a lot of changes. I also understand if you reject this feature request. Could you please advice if this is going to happen?

Thank you for your awesome skin.

**Comment by gade01** [comment]
@J4gQBqqR 
We are a bunch of Team Kodi members regularly updating Confluence with new features, updates and bugfixes.
But we are pretty busy with a bunch of other stuff as well. And upscaling to 4K would require completely new textures and for all code to be converted.

I have no time to do this, but feel free to create a PR upscaling Confluence to 4K, and I'll be happy to review it.

**Comment by HitcherUK** [comment]
Closing as it's probably never going to happen.
