### ISSUE TITLE
Seekbar Issues on Nexus

### ISSUE THREAD

**Issue by bxrye** [xbmc/skin.confluence#193]
I upgraded to the latest Kodi 20 and found that during a 10 minute skip/seek (up arrow on remote) the seekbar in the upper right hand corner no longer shows. If I use the small skip (right arrow or left arrow on remote) the seekbar is displayed. Anyone know how to fix this? I've attached a photo of the seekbar in question. Any other skin does not appear to have this problem. It's reproducible on Android or Windows. I've tested both.  

Thanks.    

![500px-Seekbarorg](https://user-images.githubusercontent.com/123170378/213692661-c6bf71f0-031a-4089-a881-4b5e30f45a06.png)

**Comment by bossanova808** [comment]
I've done fixes for the seek issue here: https://github.com/bossanova808/skin.confluence/commit/e9e3ae316856649ca3b9a5670ea44a8e95c547e1

Also includes repairs to the video calibration side of things, which is broken.

I am not sure when I will have time to do a clean PR here, though...but for anyone happy in the short term to patch their skin locally, these are necessary changes for Nexus...
