### ISSUE TITLE
Poster Thumbnails in folders are gone AND scanning individual files to the library is gone.

### ISSUE THREAD

**Issue by froSTed1030** [xbmc/skin.confluence#195]
Kodi 20 Nvidia Shield Pro Confluence
After the update, you can no longer scan individual video files to the library. Thumbnails no longer show posters in Thumbnail view, even with local posters and ini files.
This applies to SMB network shares. I have not tested local files due to space limitations.

**Comment by bossanova808** [comment]
I don't think this is a Confluence issue - I have no issue with Thumbnails with just stock Confluence:

![image](https://user-images.githubusercontent.com/731309/215293037-a3cb3a94-4974-4106-a7d2-6478b439330f.png)

Confluence doesn't really effect Kodi's scanning procedure either, so I doubt that part of it is Confluence either. 

Are all these things working fine with Estuary?

**Comment by froSTed1030** [comment]
Since the latest Kodi update, long pressing on a video does not bring up the option to scan. Nor do thumbnails show correctly that have been scanned EXCEPT in the library.

**Comment by bossanova808** [comment]
Again, not a Confluence issue.  Am seeing exactly the same behaviour in Nexus and Matrix for this, I've just tested it - no issue with thumbnails or posters showing (with not library items) - and can e.g. 'Set Content' on the folder.  And all the conext menu options are the same for Matrix and Nexus.

I think you should open an issue in Kodi itself...and you should confirm you're not seeing these same issues in Estuary, at the very least.

**Comment by froSTed1030** [comment]
This is not an issue with earlier versions of Kodi.
The previous behavior was that posters showed AS thumbnails when browsing folders AND when a thumbnail did not show a poster you could scan them directly to the library through the alt menu by long clicking them. The option to scan individual files is gone. The posters are gone. The posters show in the library and no longer in thumbnail views in confluence when looking at thumbnail views.
This was not the case in previous versions of Kodi.

**Comment by bossanova808** [comment]
Ok, well I can't see this behaviour in either Matrix or Nexus.  I don't use .nfo files (which I presume is what you mean by .ini files).  So maybe that is why?    Without an .nfo, in thumbnail view under Videos->Files, in both, with a non library movie in a folder and poster.jpg alongside it - I see a thumbnail in thumbnail mode, as I would expect.  

But I'll leave this here, as I must be misunderstanding you.

**Comment by froSTed1030** [comment]
First, correct. .NFO files. This however does not explain why thumbnails appeared as posters when navigated by folders through SMB until this update. Nor does it explain why the option to scan an individual file to the library is no longer there. The NFO files seemed to allow the thumbnails to appear as posters in Confluence without scanning the files to the library.

**Comment by HitcherUK** [comment]
Does the same happen with Estuary?

**Comment by froSTed1030** [comment]
The purpose of my writing in here is that I have been using Kodi and Confluence since XBMC (on an actual XBOX) and this is the first time I have seen an update with a loss of features. 
I don't like Estuary as it NEVER showed posters in thumbnail views when browsing folders. I organize by folder and have for all this time.

**Comment by HitcherUK** [comment]
I just tested using the following in a new folder -

```
\test\test.mkv
\test\poster.jpg
```
When I navigated to that folder Kodi scanned and displayed the poster image.
It also displayed it using Estuary.

**Comment by froSTed1030** [comment]
Thank you for testing on your setup. 
This is not what I see, and I just tested Estuary. Looks like this is a Kodi issue not a confluence issue, however, it DOES affect confluence.
If you want to test more accurately, you will need an nvidia shield on the latest version with the newest version of Kodi, the folders are accessed through SMB. I no longer have the option to scan an individual file. Nor do posters show in the folder when viewing thumbs.

**Comment by HitcherUK** [comment]
I am using an up-to-date Shield TV and the latest Kodi but using NFS so it must an SMB problem.

**Comment by bossanova808** [comment]
So, for my own knowledge....

I am using Windows here (as my test bed anyway) - but also NFS for the share, and I have a new folder `Test` with

```
test.mp4
poster.jpg
````
...in it.

If got to Video->Files->Test and using stock Confluence, in Thumbnail view, I see:

![image](https://user-images.githubusercontent.com/731309/215356331-818d2b94-fb42-43a5-9d39-0ec186ce4e67.png)

...are you saying that is supposed to show a poster by default in the Thumbnail view?  Because I don't see that (in Matrix, either).

Is there a setting that would change that back to a Thumbnail I might have set?

**Comment by froSTed1030** [comment]
Just finished my testing in NFS.
The results are as follows: 
In the past in EVERY version of Kodi prior in Confluence posters appeared in thumbnail views as long as you scanned the content to the library or you had an NFO and jpeg in the directory along with the movie file. Long pressing the FILE allowed you to scan the file into the library pulling from a variety of sources.
In the new version of Kodi:
Posters do not appear in thumbnail views when browsing folders. The option to scan to the library is ONLY available for folders, not files.  The library will show thumbnails for previously scanned and newly scanned content.
I wiped the cache and settings for Kodi and tried again. The results are the same.
@bossanova808  What you see are the new results I see. In your case, if you right-click the file do you see the option to scan the file to the library? On the shield, scanning individual files like that does not offer the option.

**Comment by HitcherUK** [comment]
Tested once again on a folder outside of my library.

```
test\Ghost (1990)\Ghost.mkv
test\Ghost (1990)\poster.jpg
test\Ghost (1990)\movie.nfo
```

**v19**
In `test` folder -

- Kodi picks up the poster and displays it
- Context menu has no option to scan folder but does have 'Set content'

In `Ghost (1990)` folder -

- Kodi scans Ghost.mkv and displays a thumbnail of the video file
- Context menu has no option to scan file or 'Set content'

**v20**
In `test` folder -

- Kodi picks up the poster and displays it
- Context menu has no option to scan folder but does have 'Set content'

In `Ghost (1990)` folder -

- Kodi scans Ghost.mkv and displays a thumbnail of the video file
- Context menu has no option to scan file or 'Set content'

Both behave exactly the same using Confluence or Estuary.

I can only assume you have these files inside a folder that already has it content set because you'd never see the option to scan it otherwise.

**Comment by froSTed1030** [comment]
I believe the content was set for the initial folder, this is a subfolder so it should cascade.
I do not have auto scanning as resources are not great and some of the files are not named in a way that kodi sets correctly. I did those manually (which isn't an option now).
In all previous versions, I had a context menu to scan the individual file to the library. This is something I used frequently.

**Comment by froSTed1030** [comment]
Also of note, the information context menu is gone in this version.

**Comment by HitcherUK** [comment]
Tested on a folder inside my library.

```
movies\Ghost (1990)\Ghost.mkv
movies\Ghost (1990)\poster.jpg
movies\Ghost (1990)\movie.nfo
```
**v19**
In `movies` folder -

- Kodi picks up the poster and displays it
- Context menu has option to scan to library
- Pressing 'i' scans and adds to library
- `Information` is now available from the context menu

In `Ghost (1990)` folder -

- Kodi scans Ghost.mkv and displays a thumbnail of the video file
- Context menu has option to scan to library
- Pressing 'i' scans and adds to library
- `Information` is not available from the context menu

**v20**
In `movies` folder -

- Kodi picks up the poster and displays it
- Context menu has option to scan to library
- Pressing 'i' scans and adds to library
- `Information` is now available from the context menu

In `Ghost (1990)` folder -

- Kodi scans Ghost.mkv and displays a thumbnail of the video file
- Context menu has option to scan to library
- Pressing 'i' scans and adds to library
- `Information` is not available from the context menu

Both behave exactly the same using Confluence or Estuary.

**Comment by HitcherUK** [comment]
I suggest you take this issue up on the forum because it's definitely not a skin problem.

**Comment by KarellenX** [comment]
Could you please test using the "long" artwork naming format...

```
\test\test.mkv
\test\test-poster.jpg
```

**Comment by froSTed1030** [comment]
@KarellenX  Good idea, however much of the movies I have, is in that long naming format. I also have -fanart for a few.

**Comment by HitcherUK** [comment]
This time I didn't put the movie in its own folder and when I did set the content to movies I didn't use 'Movies are in separate folders that match the movie title'.

```
movies\Ghost.mkv
movies\Ghost-poster.jpg
```

**v19**
In `movies` folder before setting content type -

- Kodi picks up the Ghost-poster.jpg and displays it
- Context menu has no option to scan to library
- Pressing 'i' does nothing

In `movies` folder after setting content type -

- Kodi picks up the Ghost-poster.jpg and displays it
- Context menu has option to scan to library
- Pressing 'i' scans and adds to library
- `Information` is available from the context menu

**v20**
In `movies` folder before setting content type -

- Kodi picks up the Ghost-poster.jpg and displays it
- Context menu has no option to scan to library
- Pressing 'i' does nothing

In `movies` folder after setting content type -

- Kodi picks up the Ghost-poster.jpg and displays it
- Context menu has option to scan to library
- Pressing 'i' scans and adds to library
- `Information` is available from the context menu

Once again they both behave exactly the same using Confluence or Estuary.

If you're not getting the option to scan the item then you haven't set the content of the containing folder to movies.

**Comment by froSTed1030** [comment]
Testing, however, I set the root directory to Movies and my posters have shown up. The question is this: Why did upgrading 19 to 20 suddenly drop the root directory's settings and why are NFO files ignored if there is no selection in the root directory?? Will test the information context menu later and let you know what I find. Seems like an odd bug.

**Comment by HitcherUK** [comment]
Kodi won't know there's even an NFO to scan if the content isn't set in the first place. And even if it did it also wouldn't know what the content was.
