### ISSUE TITLE
Screen Calibration

### ISSUE THREAD

**Issue by h4nzi** [xbmc/skin.confluence#197]
Nexus - screen calibration not working

**Comment by bossanova808** [comment]
There is a fix for this in #194 

Alternatively, you can pop back to Estuary, do it there, and then back to Confluence.  But that's obviously not ideal.

**Comment by h4nzi** [comment]
It's OK. I've fixed all the issues myself.  Thanks.

**Comment by bossanova808** [comment]
@DaVukovic This can be closed too :)
