### ISSUE TITLE
Confluence ToDos

### ISSUE THREAD

**Issue by DaVukovic** [xbmc/skin.confluence#199]
This issue should be understood as a WIP and should simply list stuff I would like to do before submitting a new version to the repo(s).

* New branch for Nexus
* New branch for Omega (probably after first Kodi alpha release)
* Add "Show/Hide password option"
* Provide setting for using poster instead of thumbs for musicvideos (fixes #198 )
* look through the skinning engine changes and see if other things need to be changed as well (https://forum.kodi.tv/showthread.php?tid=363553)

Others are free to comment to this issue if they think that things need to be changed/adjusted

**Comment by jodo234** [comment]
It would be nice if ListItem.mpaa would also be shown for TV shows and not only for Movies if you open the information screen of a TV Show/Episode.

**Comment by bossanova808** [comment]
Any chance of a release being cut any time soon?  It's all quite usable with Kodi 20 and a lot better than nothing, at this point?  And if a few more people actually use it, might be motivation to keep it limping along a bit longer!

**Comment by Hitcher** [comment]
@DaVukovic closing this is as I've completed the update for Nexus.

https://github.com/xbmc/skin.confluence/pull/229
