### ISSUE TITLE
suggestion for live tv 

### ISSUE THREAD

**Issue by icarok00** [xbmc/skin.confluence#201]
Add a progress bar and playtime.

Example 

![screenshot008_mod](https://user-images.githubusercontent.com/127354342/223874269-7691dbe6-79da-4ba0-b077-3f41594a4750.png)

![VpNWJhP_d](https://user-images.githubusercontent.com/127354342/223874298-8dfb92c7-9de4-417a-8546-9d19720e0d4e.png)

**Comment by icarok00** [comment]
This is the current look 

![m7BWKtv](https://user-images.githubusercontent.com/127354342/223970108-d2724108-5042-445e-baf3-346f69c6eb30.jpg)

**Comment by bossanova808** [comment]
What PVR software are you using because I think that's your issue - the bar and info is normally there (this is with NextPVR):

![image](https://user-images.githubusercontent.com/731309/223987472-895814df-5d55-4462-9e2c-2d9341333f75.png)

**Comment by icarok00** [comment]
I use this 

![Screenshot_2023-03-09-08-48-09-686_org xbmc kodi](https://user-images.githubusercontent.com/127354342/224014812-433619cb-e6ee-4bd8-9a11-4d4f0b1c092e.jpg)

**Comment by icarok00** [comment]
Is there a solution when epgs don't have time.

![Screenshot_2023-03-09-19-08-53-649_org xbmc kodi](https://user-images.githubusercontent.com/127354342/224172611-daf8c145-4b98-4822-805d-daa9d99b269e.jpg)

**Comment by icarok00** [comment]
@bossanova808 This is the solution 

![IMG_20230309_204127](https://user-images.githubusercontent.com/127354342/224185498-26f7d5de-0e6f-4603-b3bf-0ccf13565c4f.jpg)

**Comment by bossanova808** [comment]
Anywhere that is talked about, or sample code?  Sounds like a bit of a hack but I suppose it's better than just missing stuff...

**Comment by icarok00** [comment]
@bossanova808 The code is present in the skin A Confluence ZEITGEIST

![Screenshot_2023-03-09-19-08-53-649_org xbmc kodi](https://user-images.githubusercontent.com/127354342/224445315-1f89905a-cb02-4acf-beb7-03ee7ec8bbf8.jpg)

![IMG_20230309_204127](https://user-images.githubusercontent.com/127354342/224445329-408051fd-808a-4dc9-a55b-83636119d682.jpg)

**Comment by bossanova808** [comment]
Ok well I don't really even have a way to simulate this, so given you can find the code (there's a bit more in the _includes.xml file) - why don't you go ahead and make a PR for this?  Looks like it will be quite simple, and you're the best person to test it given you're the one having the problem.  Just add those two bits of code and see how you go, then PR it (and I will be happy to then test it against a normal PVR setup to make sure nothing breaks).
