### ISSUE TITLE
Tool for editing xml Files?

### ISSUE THREAD

**Issue by harryberlin** [xbmc/skin.confluence#212]
Hello 

Which tool do you use/ prefer for editing xml files?

regards

**Comment by gade01** [comment]
I just use Notepad++
It's super fast when you have setup a lot of shortcuts, settings etc.

Others use Sublime where there is a plugin:
https://github.com/phil65/SublimeKodi

**Comment by DaVukovic** [comment]
VSCode has a plugin as well, which reloads the skin after a file is saved. 

The Sublim-Plugin is great, but outdated unfortunately. Some things do still work, but the newest skin-changes aren't included anymore. And it seems that phil is not interested in updating it anymore. 

Beside that, Sublime is a great editor. In general you are able to use any editor you like and you are familiar with. 

Personally I used vim, Sublime, Intellij, VSCode....all have their pros and cons.
