### ISSUE TITLE
EPG XMLTV Programme Icon not visible

### ISSUE THREAD

**Issue by dspdspnext** [xbmc/skin.confluence#219]
I am using "IPTV Simple PVR" for Live TV and EPG is provided with XMLTV format.
Though EPG Start time / end time and progress bar details are displayed as expected but there is no programme icon displayed from the XML. Same is visible using default Kodi skin though

Is there way to display programme icon in confluence skin?
I tried $INFO[ListItem.Icon] but it displayes channel logo instead of current programme icon from EPG
```
<programme start=" stop="" channel=""><title lang="en">some title</title>
<icon src="http://<somepath>" width="" height="">
```
Thank you

**Comment by Hitcher** [comment]
@dspdspnext can you post screenshots of the differences between Confluence and Estuary please using the Demo PVR addon so I know what to look for.

**Comment by Hitcher** [comment]
Closed as no response.
