### ISSUE TITLE
incompatible with latest nightly

### ISSUE THREAD

**Issue by Klaus1189** [xbmc/skin.confluence#227]
I downloaded KodiSetup-20240220-e085b62f-master-x64.exe | 73.4 MiB | 2024-Feb-21 03:23 from:
https://mirrors.kodi.tv/nightlies/windows/win64/master/

Confluence doesn't work with it. Is there a workaround in the meantime?

**Comment by bkuhls** [comment]
Yes: https://github.com/xbmc/skin.confluence/issues/223#issuecomment-1891047172
