### ISSUE TITLE
Please fix missing label issue in this new version. A lot addons has no label picture on the front of each row in Big List View. Just row with words.  Also the go back arrow in the 1st row is also missing too.

### ISSUE THREAD

**Issue by wuweifly** [xbmc/skin.confluence#236]

**Comment by Hitcher** [comment]
Working fine with D+.

![screenshot00003](https://github.com/xbmc/skin.confluence/assets/133808/bc03d35a-2579-4ab1-8251-47a8dd4bd169)

**Comment by wuweifly** [comment]
I am talking about those 3rd party addons for live sports games such as
Rising Tides and The Endzone 19.
No label in each row Big Lists view. See
the picture in my attchment.


All those addon has label pictures when I use the old version of Confluence
skin. But no label picture now in this new version of Confluence.

Best wishes

Kevin

**Comment by wuweifly** [comment]
![image](https://github.com/xbmc/skin.confluence/assets/162838232/0b17530d-5a2e-47d0-9309-e6c74b1e8f9d)

**Comment by wuweifly** [comment]
![image](https://github.com/xbmc/skin.confluence/assets/162838232/d65332d3-c5e3-427d-ad9e-97081a41389c)

**Comment by wuweifly** [comment]
![image](https://github.com/xbmc/skin.confluence/assets/162838232/27a1ccb1-ad8d-4cf9-9eff-6e64775f1f0e)

**Comment by wuweifly** [comment]
> Working fine with D+.
> 
> 
> 
> ![screenshot00003](https://github.com/xbmc/skin.confluence/assets/133808/bc03d35a-2579-4ab1-8251-47a8dd4bd169)
> 
> 
> 
> Which addon exactly?
> 
> 

The 3rd party sports addons: Rising Tides and The Endzone 19.

**Comment by Hitcher** [comment]
Fixed for next release.

https://github.com/xbmc/skin.confluence/commit/27b6b35db9a842cfbed0f7e918bea39c63e9280d
