### ISSUE TITLE
Showing after default set: Press 'Up' to set this item as default

### ISSUE THREAD

**Issue by bossanova808** [xbmc/skin.confluence#237]
https://github.com/xbmc/skin.confluence/blob/4b666b43b14d2bd5475e51c1c3e23e8321e06267/720p/Home.xml#L1378

I might be wrong, as I am new to this feature and am just beginning to merge all of your great work into my locally tweaked version of Confluence (just up to Nexus for now) -> but I think this Boolean is opposite to what it should be - this message should only show if the value is empty, right?  If a default has been set, we don't want this message to be popping up all the time right?

**Comment by bossanova808** [comment]
...although changing to remove the `!` , that indeed stops the message from popping up, but it also breaks navigation from the Home item (Movies, TV shows etc) - up to the Recently Added posters...

**Comment by Hitcher** [comment]
See the onload condition:

`<onload condition="String.IsEmpty(Skin.String(DefaultHomeFocusItem))">SetProperty(SetDefaultHomeItem,1,home)</onload>`

If there isn't a default item set `DefaultHomeFocusItem` then `SetDefaultHomeItem` becomes `1` so we show the message.

**Comment by bossanova808** [comment]
Yep but I am seeing the message  still, even when set (tested with vanilla Confluence 4.8.0)

**Comment by bossanova808** [comment]
(I doubr it matters here but I am using profiles and definitely seeing the message when something is set and I log in).

**Comment by Hitcher** [comment]
Is it the same with the latest fixes?

https://github.com/xbmc/skin.confluence/tree/Nexus

**Comment by bossanova808** [comment]
Yes I have all those commits in, have checked (and have restored the `!`)

Here you can see that a default is definitely set, then I go back to the main screen, but the message is there. I hit up, and only then it goes away...

https://github.com/xbmc/skin.confluence/assets/731309/767e8b86-87d1-4ea4-b6b0-5f445c709c48

**Comment by bossanova808** [comment]
Yep, checked with a diff tool to be 100% sure.  Very interesting you can't replicate...gives me a clue.

More testing - I have three profiles - a `Master Settings` (essentially unused, but I've found issues with profiles if I don't have all the actual used profiles on the same 'level' so to speak) - so two more that are used: `Adults` and `Kids`.   

First, I confirmed in the `settings.xml` for Confluence for `Adults` and `Kids` that there was a value for `DefaultHomeFocusItem` - i.e. `TV SHOWS`.  There was no value (yet) for the Master Profile

I went in to the `Master Settings` profile and hit up on TV shows when prompted in there, confirmed the value in the settings area, and then in the `settings.xml` for the skin in that profile.

...and now, in the other profiles, I am not seeing the message.  

So, looks to be a classic bug related to Profiles use.  I confirmed this behaviour across two installs (Win test-bed, CoreElec daily driver) - behaviour same with both, i.e. (only) setting the value in the Master profile fixes things.   Once done, no message, and you can set separate values for the other profiles.  It's like the value for Master is the one checked, but the value for the sub profiles is the one used...

For context, this is precisely why I have this kind of odd approach:

Master
 > Adults
 > Kids

(Adults and Kids are physically store inside the profiles folder of Master as is the default for new profiles).

I set this up years ago when having odd issues with audio settings from one profile affecting the other.  Only way I could keep them separate was like this - before that the 'Master' was Adults and there was just the Kids sub profile.

Anyway - this probably won't affect many others and I guess it's not really a skin bug, unless there's a more profile specific way of checking that value??

**Comment by bossanova808** [comment]
(NB all this tested with vanilla Confluence Nexus up to the latest commits, not my own edited version)

**Comment by MikeSiLVO** [comment]
Confirmed if I add a second profile and clear the DefaultHomeFocusItem from master. I then get the same result as you.
Definitely seems like a profiles bug but that is way above my pay grade.

**Comment by bossanova808** [comment]
@jodo234 You'll be using the released 4.8.0 rather than this updated but not yet released 4.8.0.1 I think?

Can you try the changes here?  If not best to wait and re-confirm your issue after that is out.

@MikeSiLVO Thanks for confirming, good to know it's not just me.  Those profile things are hard to pin down!

**Comment by Hitcher** [comment]
This definitely sounds like it's beyond the scope of a skin and more the way profiles are handled.

NOTE: It does get reset whenever the user hides a home item to insure the correct item gets focused.

**Comment by bossanova808** [comment]
Ok am going to close this.  Am sure if there are further issues to be dealt with they will pop up in due course.

Thanks for the attention.
