### ISSUE TITLE
Also please fix no addon picture on each column in System, Add-ons, Recently updated

### ISSUE THREAD

**Issue by wuweifly** [xbmc/skin.confluence#239]
![image](https://github.com/xbmc/skin.confluence/assets/162838232/82404a6f-c57c-4d57-bf8f-64caad4c2caf)

**Comment by Hitcher** [comment]
Already fixed for the next release: https://github.com/xbmc/skin.confluence/commit/27b6b35db9a842cfbed0f7e918bea39c63e9280d

**Comment by wuweifly** [comment]
Thanks so much.
In the Big List View, in a lot of place, the picture does not show up, only
blank space in front of each row.
Usually how long it takes for the next version to be released?

Best wishes

Kevin
