### ISSUE TITLE
Thumbnails missing from Big List view

### ISSUE THREAD

**Issue by dinsdalepiranha** [xbmc/skin.confluence#243]
Since some recent update I no longer have thumbnails in "Big List" view.  Updating the library did not fix.

Confluence 4.8.0
Kodi 20.2
Ubuntu 20.04.6

**Comment by Hitcher** [comment]
Confluence v4.8.1 was released a few weeks ago that included a fix for this.

https://github.com/xbmc/repo-skins/issues/430
