### ISSUE TITLE
Size of the Message Box

### ISSUE THREAD

**Issue by VR-Punk** [xbmc/skin.confluence#279]
Hello,

I want to change the size of the message box and the size of the picture in my phonebook that appears when the Fritzbox Call Monitor plugin shows an incoming phone call. I guess it is the same message box that appears when an addon is installed.

Thanks,

**Comment by Hitcher** [comment]
General skinning questions should be raised on the forums.

**Comment by ksooo** [comment]
> the Fritzbox Call Monitor plugin

Which add-on are we taking about exactly? There is no such add-on the official Kodi addon repository.

**Comment by VR-Punk** [comment]
https://github.com/b-jesch/service.fritzbox.callmonitor

https://repo.kodinerds.net/index.php

Which forum do you prefer ? Or which is the best for this question ?

**Comment by VR-Punk** [comment]
Is it "MessageBoxPixmap" ? Where can i find that setting ?
