### ISSUE TITLE
Home button (next to back button) not working

### ISSUE THREAD

**Issue by BugfinderPro135** [xbmc/skin.confluence#280]
On Kodi 21, the home icon (next to the back icon) on the bottom right of most screens, doesn't work.

**Comment by bossanova808** [comment]
Working just fine here (Windows, with a mouse, Kodi 21 Omega with default Confluence...and also tried with my fork) - can you give a more concrete example of where it is not working for you, and how you're trying it (e.g. mouse or with a remote, linux or whatever...)

**Comment by BugfinderPro135** [comment]
It's on an Android 11 phone, using touchscreen - a TCL 20 5G (which has a longer than 1920 screen - 2298 I think) so the background cogs in 'System' appear more oval.

**Comment by BugfinderPro135** [comment]
I couldn't install confluence 5.0.6 on an android tablet running kodi 20.5 because dependencies weren't met. I won't be updating kodi to 21.0 on it either until the 'favourites' option 'Browse into' (totally pointless) is removed or moved down the menu so that 'move up' and 'move down' are #1 and #2 respectively - moving items in favourites is worst thing about kodi, and adding unnecessary key-clicks is just stupid. Hopefully someone will write a decent plugin to make this process usable.

**Comment by bossanova808** [comment]
I can tell you on my tablet (MiPad 4) - (1920x1200) - the home button works fine everywhere for me.  So it perhaps/probably is a scaling thing indeed.

As for the rest, re: how favourites work, feel free to argue your case, but take it to the forums as that's a feature request.  (& feel free to write such a plugin, Kodi is often best when you scratch your own itch).

**Comment by Hitcher** [comment]
Tested with Kodi running at the same dimensions as your phone (1080 x 2400) and the mouse worked correctly when using the home button.

**Comment by Hitcher** [comment]
> The android virtual buttons (home, menu, back) are on screen all the time, and one button partially covers the kodi home button, making it unaccessible.

Closing as it's an Android issue. You need to disable the Navigation Bar.
