### ISSUE TITLE
Skin is overstretched using 2298x1080 display

### ISSUE THREAD

**Issue by BugfinderPro135** [xbmc/skin.confluence#285]
My phone has a display of 2298x1080 (approx 19:9) and so confluence is stretched out of proportion. Is there any way of forcing it to use a maximum of 16:9? Maybe centralising it so the excess appears as black bars equally either end of the display?

This would make the system 'cog wheels' be circular again - not oval. It would also bring the bottom-right home button back into the centre of the screen and would start working again (as it's currently being covered by Android's Menu button which takes prescident.

**Comment by Hitcher** [comment]
Here's what it looks like adding that resolution and aspect ratio to the addon.xml:

![screenshot00000](https://github.com/user-attachments/assets/7c414785-4f78-41e8-bc35-9484153d174b)

![screenshot00001](https://github.com/user-attachments/assets/24317547-6493-46a4-89e4-d90ec376c07b)

Unfortunately it would take a lot of work to get working correctly.
