### ISSUE TITLE
Kodi Omega Confluence last Update

### ISSUE THREAD

**Issue by juergen-hipp** [xbmc/skin.confluence#286]
I noticed that after the last update, the button for video text (txt) is missing from LiveTV. Confluence version 5.0.8. The button is back with version 5.0.6.

**Comment by Hitcher** [comment]
Screenshot please as I don't use PVR.

**Comment by Hitcher** [comment]
@jjd-uk It looks like the teletext button  `<control type="button" id="350">` got removed in your refactoring.

**Comment by juergen-hipp** [comment]
![kodi](https://github.com/user-attachments/assets/b8d16c85-0ea2-43c1-8b09-61b18bf172b9)
![kodi1](https://github.com/user-attachments/assets/d6425d3a-1193-4c77-939c-4bb19fd8cb46)
Confluence Vers. 5.0.6 and 5.0.8

**Comment by jjd-uk** [comment]
Not sure how that happened, will check and push a fix.

**Comment by Hitcher** [comment]
Thanks.
