### ISSUE TITLE
not working with release RPi 21.1

### ISSUE THREAD

**Issue by Deadline-Dan** [xbmc/skin.confluence#293]
You get a message about not being compatible with the new architecture. If you enable/use anyway it crashes the RPi/Kodi.

**Comment by KarellenX** [comment]
We're going to need a bit more info. Details on your hardware or link to the exact box you are using, a screenshot of the message that is displayed to start off with.

**Comment by Deadline-Dan** [comment]
After several reboots and some additional package updates the issue seems to have self resolved. I can only assume the problem was an artifact of an incomplete version update. Please disregard and close.  Thank  you.

**Comment by KarellenX** [comment]
Thanks for letting us know it resolved itself.
