### ISSUE TITLE
Leia compatible Confluence skin

### ISSUE THREAD

**Issue by Jacksuarez7** [xbmc/skin.confluence#45]
Hi,

Trying to download Confluence skin for newly installed Leia on my Nvidia Shield tv and it's been marked as incompatible....any idea if you will be updating?

**Comment by HitcherUK** [comment]
Have you tried to 'Enable' it?

**Comment by Jacksuarez7** [comment]
Hi there - thanks for the response, went in via my addons and had to update it manually so now working normally thanks for the steer and all you hard work! Really appreciated. All the best
