### ISSUE TITLE
Context menu Information about an addon

### ISSUE THREAD

**Issue by dobbelina** [xbmc/skin.confluence#46]
Hi!
I'm on Kodi v17.6 Windows 10, skin version 3.1.43
When you open the context menu "Information" about an addon, the "What's new" 
text bleeds all over if the information spans more than one line,(news tag in addon.xml)

In the Estuary skin this is not a problem.

**Comment by HitcherUK** [comment]
I'll look into it but this is really a problem with the addon you're checking as that section should only be used for a shorter and less technical deception; whereas some are filling it with their complete changelog.

**Comment by HitcherUK** [comment]
Thanks, fixed https://github.com/xbmc/skin.confluence/commit/d24b7155e8764f21abafe98a0a753e3a714e846e
