### ISSUE TITLE
Confluence menus are blank after migration from kodi 17

### ISSUE THREAD

**Issue by theyoungstone** [xbmc/skin.confluence#48]
Hi,

I have migrated from Kodi 17 to 18 and I am using Confuence.
Now when Kodi starts, the "Film", "Videos", Series", "Music",... labels don't appear into the menu.  And into System menu, some entries are blank. But I can click them to enter the menu.
If I change from Confluence to another skin and come back to Confluence, the label are here.
I use Confluence into French language with kodi on Ubuntu 18.04.
Here are images of the missing labels.
![img_20190209_205219](https://user-images.githubusercontent.com/21762148/52525670-7bd48380-2cad-11e9-9ee4-cd879205df9e.jpg)
![img_20190209_205255](https://user-images.githubusercontent.com/21762148/52525672-7d9e4700-2cad-11e9-854b-33ec7fe78bab.jpg)

**Comment by bossanova808** [comment]
Yep same issue happening here (English, Windows 10 64 bit)

**Comment by HitcherUK** [comment]
Can you post a debug log please.

**Comment by HitcherUK** [comment]
Multiple profiles?

**Comment by theyoungstone** [comment]
Yes multiple 2 profiles.
I don't know how to generate a debug log, I have to search.

**Comment by HitcherUK** [comment]
It's a Kodi profile problem. As a workaround do the following -

Create an `autoexec.py` file at the userdata folder (location for that differs per OS) and under *each* profile folder (under 'userdata/profiles/<profile-name>')

Fill it with:

```
import xbmc

xbmc.executebuiltin('ReloadSkin)')
```

**Comment by bossanova808** [comment]
Also two profiles here - that is a great tip, thanks, will try that out tonight.  Do you still need debug logs if you know the issue?

**Comment by bossanova808** [comment]
Yep, that works.  Bit of a lag for it to kick in while things start up, but at least there's text!  Thanks! 

Let me know if you do still need  debug logs...

**Comment by HitcherUK** [comment]
No debug logs needed as this is a know issue, thanks.
