### ISSUE TITLE
Version 4.6.2 Music menu

### ISSUE THREAD

**Issue by Jim70** [xbmc/skin.confluence#51]
Version 4.5.14 okay. Version 4.6.2. On selecting Music option from main screen, an extra thunbnail window  with the caption "Now Playing" appears" overlaying the usual lower folder thumbnail. This extra widow persists until back at the main screen.

**Comment by HitcherUK** [comment]
Fixed for https://github.com/xbmc/skin.confluence/commit/d37a62ac890cae49889b1979b2d4ace7b93fa82f thanks.
