### ISSUE TITLE
allow choice of home screen menu item "focus"?

### ISSUE THREAD

**Issue by nmyshkin** [xbmc/skin.confluence#57]
I've always had only three menu items on the Confluence home screen: Weather, Videos, System. Until updating to Leia, my home scree has always started with "Videos" in focus, i.e., with the two default tabs showing and any add-on shortcuts I've made.

Now the home screen opens with the focus on "System". Someone suggested to me that the focus is always on the third menu item (clearly not true for me in the past) and I did try adding another menu item before Videos. This worked, but I have no use for other menu items and really don't like the look of the home screen when focused on "System".

Is there a "simple" fix I can make myself in the accessible code?

**Comment by HitcherUK** [comment]
Add this -
`<onload>SetFocus(9000,n)</onload>`
after this line in the Home.xml -
`<defaultcontrol always="true">9000</defaultcontrol>`
where n is the item you to focus in the menu plus 1 because the first one is 0.

**Comment by nmyshkin** [comment]
Excellent. Works like a charm. Thanks!
