### ISSUE TITLE
Button for playing PVR recordings not visible

### ISSUE THREAD

**Issue by onkelenno** [xbmc/skin.confluence#70]
When I connect to my tvheadend and want to play a recording, "DialogPVRInfo.xml" doesn't show a button for playing, but shows the "Add Timer" button instead. Pressing the play button on the remote works.

Shouldn't button id 9 (Add Timer) be `<visible>Window.IsActive(PVRGuideInfo)</visible>` and 
button id 8 (Play recording) be always `visible`?

Confluence 4.6.9

**Comment by HitcherUK** [comment]
@ksooo any ideas?
