### ISSUE TITLE
Confluence "Subtitle OSD" issue.

### ISSUE THREAD

**Issue by Gamli-1** [xbmc/skin.confluence#72]
A new version of KODI, KODI 18, calls for a new version of skin. I have used Confluence for a long time now and have been very pleased with it's plain and simple way of presenting the complex and wonderful world of KODI. However, I am not pleased with the Confluence version for KODI 18. In my view this version is a step down in functionality.

I am referring to the new way subtitles are handled via OSD. The new method just does not compare with the former handling. I have of course no idea why this change was made; but possibly it was made to make the "Subtitle OSD" look like the OSD for "Video Settings" and OSD for "Audio and subtitle settings" - however, my guess does not matter.

What matters is that the workings and uses of the "Subtitle OSD" is categorically different from the other two. Having them all look alike will just do that but at the same time destroy the powerful functionality of the "Subtitle OSD" experienced in former versions of Confluence.

Using the crippled "Subtitle OSD" on Confluence for KODI 18 - the mind wanders to the good old days of former versions of Confluence and a vague kind of hope or thought surfaces: "will it be changed back...". - Of course I reverted to KODI 17 with the superior Confluence.

**Comment by HitcherUK** [comment]
Closing as this was done because of the addition of a proper subtitle dialog.

https://forum.kodi.tv/showthread.php?tid=298565&pid=2705599#pid2705599
