### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kokosz887** [xbmc/skin.confluence#76]
I would like to switch from LIBREELEC (KODI 16) to COREELEC but I would like to change the appearance of the channel change window in PVR IPTV SIMPLE CLIENT to the one I have now in LIBREELEC (photo below). COREELEC just displays a large white channel number and I don't quite like it. Can I go back to the old version of the channel change in the CONFLUENCE skin?

![1](https://user-images.githubusercontent.com/28668535/72814311-234f8980-3c65-11ea-9bcb-bfe3bf9b4232.jpg)

**Comment by HitcherUK** [comment]
You're better off asking on the forums.
