### ISSUE TITLE
Subtitle icon always visible even if no subtitles are enabled

### ISSUE THREAD

**Issue by Sopor** [xbmc/skin.confluence#78]
When playing a video there are two symbols that show the sound and subtitle languages. In Kodi 18.x it is now showing the subtitle language even if the subtitles are not enabled. This is the only way to quickly see if the subtitles are enabled or disabled, but now that isn't possible anymore because this symbol is always there when a video has subtitles.

![image](https://user-images.githubusercontent.com/5789283/79517197-c68a2200-804d-11ea-9fc7-7941bf7b9635.png)

Kodi version: 18.6
Confluence version: 4.6.9

**Comment by HitcherUK** [comment]
Nothing has changed on the skin code side of things so it must be a change to the way the skinning engine now handles `VideoPlayer.SubtitlesLanguage` because it was empty unless subtitles were enabled but now it's not.

**Comment by gade01** [comment]
I submitted a PR with a fix.

**Comment by Sopor** [comment]
I wonder why my report was closed so fast?

Thanks @gade01 for doing something about it 👍
