### ISSUE TITLE
Player controls (OSD) won't automatically close after downloading subtitles

### ISSUE THREAD

**Issue by Sopor** [xbmc/skin.confluence#79]
When downloading subtitles in 17.6 the player controls (OSD) did always close it self when the subtitle was downloaded, but in 18.6 i have to close it manually. Most of the time you are done when you have selected the subtitle, but now you have to wait for it and when it is finished you have to press the back button to close the OSD :(

Kodi 18.6
Confluence 4.6.9

**Comment by HitcherUK** [comment]
What happens on Estuary?

**Comment by Sopor** [comment]
The same.
I assume it has something to do with that extra window that 18.x have? In Kodi 17.6 it was possible to select `Download` from the subtitle button in the OSD and when you press `Download` it closes the OSD, so when the subtitle was downloaded the OSD was already closed.
![image](https://user-images.githubusercontent.com/5789283/79923318-86ec7d00-8435-11ea-90fe-60e3c8543be2.png)


You also need to have `Enable mouse and touch screen support` disabled. If you use a mouse the OSD will auto-hide.

**Comment by HitcherUK** [comment]
This is due to Kodi core changes to the subtitle dialog.
