### ISSUE TITLE
No weekdays on home screen when running Swedish language

### ISSUE THREAD

**Issue by Sopor** [xbmc/skin.confluence#86]
When i run Kodi with the Confluence skin it seems that the weekdays are missing when i use Swedish language.
So instead of `Lördag den 19 september 2020` it will show `den 19 september 2020`

![image](https://user-images.githubusercontent.com/5789283/93672225-77876380-faa9-11ea-8693-3817cba5286b.png)

![image](https://user-images.githubusercontent.com/5789283/93672321-5bd08d00-faaa-11ea-8472-e9cce11f92db.png)

Kodi 18.8
Confluence 4.6.9
Windows 10

Btw, month should use lowercase letter, but that is another issue :)

**Comment by gade01** [comment]
I can see what you mean.

Confluence uses the infolabel System.Date and returns whatever is provided by that label.
So it's not an issue with Confluence, - more an issue with Kodi core.

Regarding the uppercase/lowercase letters: that's how Swedish is translated at Transifex.

**Comment by Sopor** [comment]
After some more investigation it seems that it will show the same in Windows:

Swedish regional format in Windows 10:
![image](https://user-images.githubusercontent.com/5789283/94639195-02ebca80-02dc-11eb-9288-9be861c1766e.png)

English regional format in Windows 10:
![image](https://user-images.githubusercontent.com/5789283/94639269-33336900-02dc-11eb-94bf-674722a1f70f.png)

So i'm closing this!
