### ISSUE TITLE
Confluence 4.7.6 not showing season posters

### ISSUE THREAD

**Issue by guenniguenzelsen** [xbmc/skin.confluence#91]
TV-show season posters are not displayed in Kodi 19 RC1
Skin: Confluence 4.7.6
Not working in this view: Media info 2, Media info 3, Big List
Working in this view: List, Thumbnail, Poster Wrap
Poster naming (example): season01-poster.jpg

Operating system version/name: 1: Windows 10 64bit / 2: Libreelec 9.80 nightly / 3: FireOS
Kodi version: 19 RC1

**Comment by HitcherUK** [comment]
Fixed.
